# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 40, 801, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.bcdi = QtWidgets.QWidget()
        self.bcdi.setObjectName("bcdi")
        self.xray_energy = QtWidgets.QLineEdit(self.bcdi)
        self.xray_energy.setGeometry(QtCore.QRect(30, 30, 111, 20))
        self.xray_energy.setText("")
        self.xray_energy.setObjectName("xray_energy")
        self.label_energy = QtWidgets.QLabel(self.bcdi)
        self.label_energy.setGeometry(QtCore.QRect(40, 10, 101, 20))
        self.label_energy.setObjectName("label_energy")
        self.xray_wavelength = QtWidgets.QLineEdit(self.bcdi)
        self.xray_wavelength.setGeometry(QtCore.QRect(190, 30, 113, 20))
        self.xray_wavelength.setObjectName("xray_wavelength")
        self.label_wavelength = QtWidgets.QLabel(self.bcdi)
        self.label_wavelength.setGeometry(QtCore.QRect(190, 10, 111, 20))
        self.label_wavelength.setObjectName("label_wavelength")
        self.detector_distance = QtWidgets.QLineEdit(self.bcdi)
        self.detector_distance.setGeometry(QtCore.QRect(350, 30, 113, 20))
        self.detector_distance.setObjectName("detector_distance")
        self.label = QtWidgets.QLabel(self.bcdi)
        self.label.setGeometry(QtCore.QRect(350, 9, 111, 21))
        self.label.setObjectName("label")
        self.detector_pixelsize = QtWidgets.QLineEdit(self.bcdi)
        self.detector_pixelsize.setGeometry(QtCore.QRect(510, 30, 113, 20))
        self.detector_pixelsize.setObjectName("detector_pixelsize")
        self.label_2 = QtWidgets.QLabel(self.bcdi)
        self.label_2.setGeometry(QtCore.QRect(510, 10, 111, 20))
        self.label_2.setObjectName("label_2")
        self.fringe_spacing = QtWidgets.QLineEdit(self.bcdi)
        self.fringe_spacing.setGeometry(QtCore.QRect(30, 110, 113, 20))
        self.fringe_spacing.setObjectName("fringe_spacing")
        self.label_4 = QtWidgets.QLabel(self.bcdi)
        self.label_4.setGeometry(QtCore.QRect(30, 90, 111, 16))
        self.label_4.setObjectName("label_4")
        self.crystal_size = QtWidgets.QLineEdit(self.bcdi)
        self.crystal_size.setGeometry(QtCore.QRect(190, 110, 113, 20))
        self.crystal_size.setObjectName("crystal_size")
        self.label_5 = QtWidgets.QLabel(self.bcdi)
        self.label_5.setGeometry(QtCore.QRect(190, 90, 111, 20))
        self.label_5.setObjectName("label_5")
        self.angular_sampling = QtWidgets.QLineEdit(self.bcdi)
        self.angular_sampling.setGeometry(QtCore.QRect(190, 190, 113, 20))
        self.angular_sampling.setObjectName("angular_sampling")
        self.label_3 = QtWidgets.QLabel(self.bcdi)
        self.label_3.setGeometry(QtCore.QRect(190, 170, 111, 16))
        self.label_3.setObjectName("label_3")
        self.min_detector_distance = QtWidgets.QLineEdit(self.bcdi)
        self.min_detector_distance.setGeometry(QtCore.QRect(350, 110, 113, 20))
        self.min_detector_distance.setStyleSheet(
            "background-color: rgb(230, 230, 230);"
        )
        self.min_detector_distance.setReadOnly(True)
        self.min_detector_distance.setObjectName("min_detector_distance")
        self.label_6 = QtWidgets.QLabel(self.bcdi)
        self.label_6.setGeometry(QtCore.QRect(350, 90, 111, 16))
        self.label_6.setObjectName("label_6")
        self.rocking_angle = QtWidgets.QLineEdit(self.bcdi)
        self.rocking_angle.setGeometry(QtCore.QRect(30, 190, 113, 20))
        self.rocking_angle.setObjectName("rocking_angle")
        self.label_7 = QtWidgets.QLabel(self.bcdi)
        self.label_7.setGeometry(QtCore.QRect(30, 170, 111, 16))
        self.label_7.setObjectName("label_7")
        self.max_rocking_angle = QtWidgets.QLineEdit(self.bcdi)
        self.max_rocking_angle.setGeometry(QtCore.QRect(350, 190, 113, 20))
        self.max_rocking_angle.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.max_rocking_angle.setReadOnly(True)
        self.max_rocking_angle.setObjectName("max_rocking_angle")
        self.label_8 = QtWidgets.QLabel(self.bcdi)
        self.label_8.setGeometry(QtCore.QRect(350, 170, 111, 16))
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.bcdi, "")
        self.diffraction = QtWidgets.QWidget()
        self.diffraction.setObjectName("diffraction")
        self.tabWidget.addTab(self.diffraction, "")
        self.cdi = QtWidgets.QWidget()
        self.cdi.setObjectName("cdi")
        self.tabWidget.addTab(self.cdi, "")
        self.helptext = QtWidgets.QLineEdit(self.centralwidget)
        self.helptext.setEnabled(True)
        self.helptext.setGeometry(QtCore.QRect(10, 10, 781, 21))
        self.helptext.setReadOnly(True)
        self.helptext.setObjectName("helptext")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_energy.setText(_translate("MainWindow", "X-ray energy (keV)"))
        self.label_wavelength.setText(_translate("MainWindow", "Wavelength (A)"))
        self.label.setText(_translate("MainWindow", "Detector distance (m)"))
        self.label_2.setText(_translate("MainWindow", "Detector pixel size (um)"))
        self.label_4.setText(_translate("MainWindow", "Fringe spacing / sampling"))
        self.label_5.setText(_translate("MainWindow", "Crystal size (nm)"))
        self.label_3.setText(_translate("MainWindow", "Angular sampling"))
        self.label_6.setText(_translate("MainWindow", "Minimum detector distance (m)"))
        self.label_7.setText(_translate("MainWindow", "Rocking angle (deg)"))
        self.label_8.setText(_translate("MainWindow", "Maximum rocking angle (deg)"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.bcdi),
            _translate("MainWindow", "BCDI calculations"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.diffraction),
            _translate("MainWindow", "Diffraction calculations"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.cdi),
            _translate("MainWindow", "CDI calculations"),
        )
