# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(759, 563)
        main_window.setStyleSheet("background-color: rgb(204, 131, 255);")
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.helptext = QtWidgets.QLineEdit(self.centralwidget)
        self.helptext.setEnabled(True)
        self.helptext.setStyleSheet(
            "background-color: rgb(51, 51, 51);\n" "color: rgb(255, 255, 255);"
        )
        self.helptext.setReadOnly(True)
        self.helptext.setObjectName("helptext")
        self.verticalLayout.addWidget(self.helptext)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("background-color: rgb(197, 243, 242);")
        self.tabWidget.setObjectName("tabWidget")
        self.bcdi = QtWidgets.QWidget()
        self.bcdi.setObjectName("bcdi")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.bcdi)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_energy = QtWidgets.QLabel(self.bcdi)
        self.label_energy.setObjectName("label_energy")
        self.verticalLayout_3.addWidget(self.label_energy)
        self.xray_energy = QtWidgets.QLineEdit(self.bcdi)
        self.xray_energy.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.xray_energy.setText("")
        self.xray_energy.setObjectName("xray_energy")
        self.verticalLayout_3.addWidget(self.xray_energy)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_wavelength = QtWidgets.QLabel(self.bcdi)
        self.label_wavelength.setObjectName("label_wavelength")
        self.verticalLayout_4.addWidget(self.label_wavelength)
        self.xray_wavelength = QtWidgets.QLineEdit(self.bcdi)
        self.xray_wavelength.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.xray_wavelength.setObjectName("xray_wavelength")
        self.verticalLayout_4.addWidget(self.xray_wavelength)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.bcdi)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.detector_distance = QtWidgets.QLineEdit(self.bcdi)
        self.detector_distance.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.detector_distance.setObjectName("detector_distance")
        self.verticalLayout_5.addWidget(self.detector_distance)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.bcdi)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.detector_pixelsize = QtWidgets.QLineEdit(self.bcdi)
        self.detector_pixelsize.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.detector_pixelsize.setObjectName("detector_pixelsize")
        self.verticalLayout_6.addWidget(self.detector_pixelsize)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_10.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_10.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.bcdi)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.fringe_spacing = QtWidgets.QLineEdit(self.bcdi)
        self.fringe_spacing.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fringe_spacing.setObjectName("fringe_spacing")
        self.verticalLayout_7.addWidget(self.fringe_spacing)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        spacerItem4 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.bcdi)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.crystal_size = QtWidgets.QLineEdit(self.bcdi)
        self.crystal_size.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.crystal_size.setObjectName("crystal_size")
        self.verticalLayout_8.addWidget(self.crystal_size)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        spacerItem5 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.bcdi)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_9.addWidget(self.label_6)
        self.min_detector_distance = QtWidgets.QLineEdit(self.bcdi)
        self.min_detector_distance.setStyleSheet(
            "background-color: rgb(230, 230, 230);"
        )
        self.min_detector_distance.setReadOnly(True)
        self.min_detector_distance.setObjectName("min_detector_distance")
        self.verticalLayout_9.addWidget(self.min_detector_distance)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_10.addItem(spacerItem6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.bcdi)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_11.addWidget(self.label_7)
        self.rocking_angle = QtWidgets.QLineEdit(self.bcdi)
        self.rocking_angle.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.rocking_angle.setObjectName("rocking_angle")
        self.verticalLayout_11.addWidget(self.rocking_angle)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        spacerItem7 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_3 = QtWidgets.QLabel(self.bcdi)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_12.addWidget(self.label_3)
        self.angular_sampling = QtWidgets.QLineEdit(self.bcdi)
        self.angular_sampling.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.angular_sampling.setObjectName("angular_sampling")
        self.verticalLayout_12.addWidget(self.angular_sampling)
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        spacerItem8 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_8 = QtWidgets.QLabel(self.bcdi)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_13.addWidget(self.label_8)
        self.max_rocking_angle = QtWidgets.QLineEdit(self.bcdi)
        self.max_rocking_angle.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.max_rocking_angle.setReadOnly(True)
        self.max_rocking_angle.setObjectName("max_rocking_angle")
        self.verticalLayout_13.addWidget(self.max_rocking_angle)
        self.horizontalLayout_4.addLayout(self.verticalLayout_13)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.verticalLayout_15.addLayout(self.verticalLayout_10)
        self.tabWidget.addTab(self.bcdi, "")
        self.cdi = QtWidgets.QWidget()
        self.cdi.setObjectName("cdi")
        self.tabWidget.addTab(self.cdi, "")
        self.diffraction = QtWidgets.QWidget()
        self.diffraction.setObjectName("diffraction")
        self.tabWidget.addTab(self.diffraction, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        main_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_window)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "CDICALC"))
        self.label_energy.setText(_translate("main_window", "X-ray energy (keV)"))
        self.label_wavelength.setText(_translate("main_window", "Wavelength (A)"))
        self.label.setText(_translate("main_window", "Detector distance (m)"))
        self.label_2.setText(_translate("main_window", "Detector pixel size (um)"))
        self.label_4.setText(
            _translate("main_window", "Fringe spacing (pixel)\n" "/ sampling")
        )
        self.label_5.setText(_translate("main_window", "Crystal size (nm)"))
        self.label_6.setText(_translate("main_window", "Min detector distance (m)"))
        self.label_7.setText(_translate("main_window", "Rocking angle (deg)"))
        self.label_3.setText(_translate("main_window", "Angular sampling"))
        self.label_8.setText(_translate("main_window", "Max rocking angle (deg)"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.bcdi),
            _translate("main_window", "BCDI calculations"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.cdi),
            _translate("main_window", "CDI calculations"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.diffraction),
            _translate("main_window", "Diffraction calculations"),
        )
