# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 40, 801, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.bcdi = QtWidgets.QWidget()
        self.bcdi.setObjectName("bcdi")
        self.energy = QtWidgets.QLineEdit(self.bcdi)
        self.energy.setGeometry(QtCore.QRect(30, 30, 91, 20))
        self.energy.setText("")
        self.energy.setObjectName("energy")
        self.label_energy = QtWidgets.QLabel(self.bcdi)
        self.label_energy.setGeometry(QtCore.QRect(40, 10, 71, 20))
        self.label_energy.setObjectName("label_energy")
        self.wavelength = QtWidgets.QLineEdit(self.bcdi)
        self.wavelength.setGeometry(QtCore.QRect(180, 30, 113, 20))
        self.wavelength.setObjectName("wavelength")
        self.label_wavelength = QtWidgets.QLabel(self.bcdi)
        self.label_wavelength.setGeometry(QtCore.QRect(200, 10, 81, 20))
        self.label_wavelength.setObjectName("label_wavelength")
        self.distance = QtWidgets.QLineEdit(self.bcdi)
        self.distance.setGeometry(QtCore.QRect(340, 30, 113, 20))
        self.distance.setObjectName("distance")
        self.label = QtWidgets.QLabel(self.bcdi)
        self.label.setGeometry(QtCore.QRect(350, 9, 111, 21))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.bcdi, "")
        self.diffraction = QtWidgets.QWidget()
        self.diffraction.setObjectName("diffraction")
        self.tabWidget.addTab(self.diffraction, "")
        self.cdi = QtWidgets.QWidget()
        self.cdi.setObjectName("cdi")
        self.tabWidget.addTab(self.cdi, "")
        self.helptext = QtWidgets.QLineEdit(self.centralwidget)
        self.helptext.setEnabled(True)
        self.helptext.setGeometry(QtCore.QRect(10, 10, 781, 21))
        self.helptext.setReadOnly(True)
        self.helptext.setObjectName("helptext")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_energy.setText(_translate("MainWindow", "X-ray energy (keV)"))
        self.label_wavelength.setText(_translate("MainWindow", "Wavelength (A)"))
        self.label.setText(_translate("MainWindow", "Detector distance (m)"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.bcdi),
            _translate("MainWindow", "BCDI calculations"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.diffraction),
            _translate("MainWindow", "Diffraction calculations"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.cdi),
            _translate("MainWindow", "CDI calculations"),
        )
